function update_date=get_update_date(month_date)
day1=cell2mat(month_date(1));%开始日
day2=cell2mat(month_date(end));%结束日
%拆分日期到年月日
s=datevec(day1);
e=datevec(day2);
s=s(1:3);
e=e(1:3);
%第一更新日
if(s(2)>=7)
    update1=[s(1),6,eomday(s(1),6)];
else
    update1=[s(1)-1,12,eomday(s(1)-1,12)];
end
%最后更新日
if(e(2)>=7)
    update2=[e(1),6,eomday(e(1),6)];
else
    update2=[e(1)-1,12,eomday(e(1)-1,12)];
end
%项数
series_num=(update2(1)-update1(1))*2+(update2(2)-update1(2))/6+1;
%更新日数值形式
update_date_num(1,:)=update1;
for(i=2:series_num)
    update_date_num(i,1)=update_date_num(i-1,1);
    update_date_num(i,2)=update_date_num(i-1,2)+6;
    if(update_date_num(i,2)>12)
        update_date_num(i,2)=update_date_num(i,2)-12;
        update_date_num(i,1)=update_date_num(i,1)+1;
    end
    update_date_num(i,3)=eomday(update_date_num(i,1),update_date_num(i,2));
end
%将数值型日期转换为cell形式
[m,n]=size(update_date_num);
for(i=1:m)
    update_date(i)=cellstr(datestr(datenum(update_date_num(i,1),update_date_num(i,2),update_date_num(i,3)),26));
end
end
